"""Construction des widgets ; orchestration conservée dans Application."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QCheckBox, QFrame, QHBoxLayout, QVBoxLayout, QWidget
from vaultsafe.ui.composants import BoutonOptions, Symbole, bouton, champ, defilement, etiquette


def construire_connexion(self, existe=True, pret=True, automatique=False):
    self.login_existe = existe
    self.poignee.hide()
    page = QWidget()
    layout = QVBoxLayout(page)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(0)
    commandes = self.commandes()
    commandes.ligne.setContentsMargins(12, 4, 12, 0)
    layout.addWidget(commandes)
    contenu = QWidget()
    contenu.setObjectName('connexion')
    corps = QVBoxLayout(contenu)
    facteur = self.echelle / 100
    corps.setContentsMargins(round(32 * facteur), round(16 * facteur), round(32 * facteur), round((24 if existe else 12) * facteur))
    corps.setSpacing(0)
    marque = QVBoxLayout()
    marque.setSpacing(round(10 * facteur))
    marque.addWidget(Symbole('logo', self.couleurs['accent'], 48), alignment=Qt.AlignmentFlag.AlignHCenter)
    nom = QWidget()
    nom_ligne = QHBoxLayout(nom)
    nom_ligne.setContentsMargins(0, 0, 0, 0)
    nom_ligne.setSpacing(0)
    nom_ligne.addWidget(etiquette('Vault', 'marque_connexion_noire'))
    nom_ligne.addWidget(etiquette('Safe', 'marque_connexion'))
    marque.addWidget(nom, alignment=Qt.AlignmentFlag.AlignHCenter)
    corps.addLayout(marque)
    corps.addSpacing(round(22 * facteur))
    titre = etiquette('Connexion' if existe else 'Créer votre accès', 'titre_connexion')
    titre.setAlignment(Qt.AlignmentFlag.AlignCenter)
    corps.addWidget(titre)
    corps.addSpacing(round(5 * facteur))
    aide = etiquette('Saisissez votre mot de passe maître.' if existe else
        'Choisissez un mot de passe maître d’au moins 12 caractères.', 'aide_connexion')
    aide.setAlignment(Qt.AlignmentFlag.AlignCenter)
    corps.addWidget(aide)
    corps.addSpacing(round(24 * facteur))
    corps.addWidget(etiquette('Mot de passe maître', 'libelle_connexion'))
    corps.addSpacing(round(7 * facteur))
    self.mot_maitre = champ(secret=True, indication='Votre mot de passe', oeil=True)
    self.mot_maitre.setObjectName('mot_maitre')
    self.mot_maitre.setAccessibleName('Mot de passe maître')
    self.mot_maitre.setMinimumHeight(round(44 * facteur))
    corps.addWidget(self.mot_maitre)
    self.confirmation_maitre = champ(secret=True, indication='Confirmer le mot de passe', oeil=True)
    self.confirmation_maitre.setObjectName('confirmation_maitre')
    self.confirmation_maitre.setAccessibleName('Confirmer le mot de passe maître')
    self.confirmation_maitre.setVisible(not existe)
    self.confirmation_maitre.setMinimumHeight(round(44 * facteur))
    if not existe:
        corps.addSpacing(round(12 * facteur))
    corps.addWidget(self.confirmation_maitre)
    if existe:
        corps.addSpacing(round(6 * facteur))
        self.recuperer_login = bouton('Mot de passe oublié ?', self.recuperation, 'lien')
        self.recuperer_login.setMinimumHeight(round(28 * facteur))
        corps.addWidget(self.recuperer_login, alignment=Qt.AlignmentFlag.AlignRight)
    self.erreur_login = etiquette('Chargement du coffre…' if not pret else '', 'erreur')
    self.erreur_login.setObjectName('erreur_connexion')
    corps.addWidget(self.erreur_login)
    self.case_appareil = QCheckBox('Faire confiance à cet appareil · 30 jours')
    self.case_appareil.setEnabled(pret)
    corps.addWidget(self.case_appareil)
    corps.addSpacing(round(12 * facteur))
    self.bouton_login = bouton('Se connecter' if existe else 'Créer le coffre', self.connecter, 'principal')
    self.bouton_login.setMinimumHeight(round(44 * facteur))
    self.bouton_login.setEnabled(pret)
    self.mot_maitre.setEnabled(pret)
    self.mot_maitre.returnPressed.connect(self.connecter)
    self.confirmation_maitre.returnPressed.connect(self.connecter)
    corps.addWidget(self.bouton_login)
    self.bouton_appareil = bouton('Ouvrir avec cet appareil', self.connecter_appareil, 'lien')
    self.bouton_appareil.hide()
    corps.addWidget(self.bouton_appareil)
    corps.addSpacing(round(20 * facteur))
    separateur = QHBoxLayout()
    separateur.setSpacing(round(10 * facteur))
    self.options_login = BoutonOptions('Autres options')
    self.options_login.setMinimumHeight(round(28 * facteur))
    for i in range(3):
        if i == 1:
            separateur.addWidget(self.options_login)
        else:
            trait = QFrame()
            trait.setObjectName('separateur_connexion')
            trait.setFixedHeight(1)
            separateur.addWidget(trait, 1)
    corps.addLayout(separateur)
    self.choix_coffre_login = QWidget()
    options = QVBoxLayout(self.choix_coffre_login)
    options.setContentsMargins(0, round(6 * facteur), 0, 0)
    options.setSpacing(round(6 * facteur))
    options.addWidget(bouton('Ouvrir un coffre', self.choisir_coffre, symbole='dossier'))
    options.addWidget(bouton('Créer un autre coffre', lambda: self.choisir_coffre(True), symbole='plus'))
    self.choix_coffre_login.hide()
    self.options_login.toggled.connect(self.choix_coffre_login.setVisible)
    corps.addWidget(self.choix_coffre_login)
    corps.addStretch()
    self.zone_connexion = defilement(contenu)
    layout.addWidget(self.zone_connexion, 1)
    self.remplacer(page)
    self.mot_maitre.setFocus()
    if pret and existe and self.appareil:
        self.verifier_appareil(automatique)
